# Generated by Django 4.1 on 2023-04-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BngJobs',
            new_name='BngJob',
        ),
        migrations.RenameModel(
            old_name='PuneJobs',
            new_name='HydJob',
        ),
        migrations.RenameModel(
            old_name='HydJobs',
            new_name='PuneJob',
        ),
    ]
